language: generic
sudo: false
dist: trusty

env:
  matrix:
    - PYTHON=3.6

install:
  - source continuous_integration/travis/install.sh

script:
  - source continuous_integration/travis/run_tests.sh
  - flake8 distributed

after_success:
  - if [[ $COVERAGE == true ]]; then coverage report; pip install -q coveralls ; coveralls ; fi

notifications:
  email: false
