language: generic
# sudo shouldn't be required, but currently tests fail when run in a container
# on travis instead of a vm. See https://github.com/dask/distributed/pull/1563.
sudo: required
dist: trusty

env:
  matrix:
    - PYTHON=3.6 TESTS=true COVERAGE=true PACKAGES="lz4" TORNADO=5 CRICK=true
    - PYTHON=3.7 TESTS=true PACKAGES="python-snappy python-blosc" TORNADO=6
    - PYTHON=3.8 TESTS=true PACKAGES="python-snappy python-blosc" TORNADO=6

matrix:
  fast_finish: true
  include:
  - os: osx
    env: PYTHON=3.7 TESTS=true PACKAGES="python-snappy python-blosc" TORNADO=6
    if: type != pull_request OR commit_message =~ test-osx  # Skip on PRs unless the commit message contains "test-osx"

  allow_failures:
    - os: osx

install:
  - if [[ $TESTS == true ]]; then source continuous_integration/travis/install.sh ; fi
  - if [[ $TESTS == true ]]; then source continuous_integration/travis/setup-ssh.sh ; fi

script:
  - if [[ $TESTS == true ]]; then source continuous_integration/travis/run_tests.sh ; fi

after_success:
  - if [[ $COVERAGE == true ]]; then coverage report; python -m pip install -q coveralls ; coveralls ; fi

notifications:
  email: false
