language: generic
# sudo shouldn't be required, but currently tests fail when run in a container
# on travis instead of a vm. See https://github.com/dask/distributed/pull/1563.
sudo: required
dist: trusty

env:
  matrix:
    - PYTHON=2.7 PACKAGES="python-blosc futures faulthandler"
    - PYTHON=3.5.4 COVERAGE=true PACKAGES=python-blosc CRICK=true
    - PYTHON=3.6

matrix:
  fast_finish: true
  include:
  - os: osx
    env: PYTHON=3.6 RUNSLOW=false
  # Tornado dev builds disabled, as Bokeh and IPython choke on it
  #- env: PYTHON=3.6 TORNADO=dev
  #- env: PYTHON=2.7 TORNADO=dev RUNSLOW=false PACKAGES="futures faulthandler"
  # Together with fast_finish, allow build to be marked successful before the OS X job finishes
  allow_failures:
  - os: osx
    # This needs to be the exact same line as above
    env: PYTHON=3.6 RUNSLOW=false

install:
  - source continuous_integration/travis/install.sh

script:
  - source continuous_integration/travis/run_tests.sh
  - flake8 distributed

after_success:
  - if [[ $COVERAGE == true ]]; then coverage report; pip install -q coveralls ; coveralls ; fi

notifications:
  email: false
