language: generic
sudo: false
dist: trusty
services:
  - docker

env:
  matrix:
    - PYTHON=2.7 PACKAGES="blosc futures faulthandler"
    - PYTHON=3.5 COVERAGE=true PACKAGES=blosc CRICK=true
    - PYTHON=3.6
    - HDFS=true PYTHON=2.7
    - HDFS=true PYTHON=3.5 PACKAGES=blosc

matrix:
  fast_finish: true
  #include:
  #- os: osx
    #env: PYTHON=3.6 RUNSLOW=false
  ## Together with fast_finish, allow build to be marked successful before the OS X job finishes
  #allow_failures:
  #- os: osx
    ## This needs to be the exact same line as above
    #env: PYTHON=3.6 RUNSLOW=false

addons:
  hosts:
    # Need to make the container's hostname resolvable, since the HDFS
    # client will contact it back.
    - hdfs-container

before_install:
  - |
    if [[ $HDFS == true ]]; then
        pushd continuous_integration
        docker build -t distributed-hdfs-test .
        # Run HDFS
        ./run-hdfs.sh || exit 1
        popd
    fi;

install:
  - source continuous_integration/travis/install.sh

script:
  - source continuous_integration/travis/run_tests.sh
  - flake8 distributed/*.py distributed/{bokeh,comm,deploy,protocol}/*.py # no tests yet

after_success:
  - if [[ $COVERAGE == true ]]; then coverage report; pip install -q coveralls ; coveralls ; fi

notifications:
  email: false
