codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85...100"

  # Prevent red "X"s from showing up on PR checks
  # before all CI builds have completed
  notify:
    wait_for_ci: yes

  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch: no
    changes: no

comment: off
