version: 2

jobs:
  build:
    docker:
      - image: circleci/python
    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-test"

    steps:
      - checkout
      - restore_cache:
          keys:
            - miniconda-v1-{{ checksum ".circleci/environment-3.6.yml" }}
      - run:
          name: install miniconda
          command: |
              if [ ! -d "/home/circleci/miniconda" ]; then
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
                bash miniconda.sh -b -p $HOME/miniconda
                export PATH="$HOME/miniconda/bin:$PATH"
                conda config --set always_yes yes --set changeps1 no
              fi
              sudo chown -R $USER.$USER $HOME
      - run:
          name: configure conda
          command: |
              export PATH="$HOME/miniconda/bin:$PATH"
              if [ ! -d "/home/circleci/miniconda/envs/test-dask" ]; then
                conda update -q conda
                conda env create -f .circleci/environment-3.6.yml --name=test-dask
                source activate test-dask
                pip install --no-deps --quiet -e .
              fi
              conda env list
              conda list ${ENV_NAME}
      - save_cache:
          key: miniconda-v1-{{ checksum ".circleci/environment-3.6.yml" }}
          paths:
            - "/home/circleci/miniconda"

      - run:
          name: pip install co-dependencies
          command: |
            /home/circleci/miniconda/envs/test-dask/bin/pip install -q git+https://github.com/dask/dask.git --no-deps --upgrade
      - run:
          name: py.test
          command: |
            /home/circleci/miniconda/envs/test-dask/bin/py.test distributed --verbose
      - run:
          name: flake8
          command: |
            /home/circleci/miniconda/envs/test-dask/bin/flake8 distributed
