version: 2

jobs:
  build:
    docker:
      - image: circleci/python
    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-test"

    steps:
      - checkout
      - run:
          name: install
          command: source continuous_integration/travis/install.sh
      - run:
          name: test
          command: |
              export PATH=/home/circleci/miniconda/envs/$ENV_NAME/bin:$PATH
              source continuous_integration/travis/run_tests.sh
