version: 2

jobs:
  build:
    docker:
      - image: circleci/python
    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-test"

    steps:
      - checkout
      - run:
          name: install
          command: source continuous_integration/travis/install.sh
      - run:
          name: test
          command: |
              /home/circleci/miniconda/envs/dask-test/bin/py.test -m "not avoid travis" distributed --verbose
