package:
  name: boto3
  version: "1.2.3"

source:
  fn: boto3-1.2.3.tar.gz
  url: https://pypi.python.org/packages/source/b/boto3/boto3-1.2.3.tar.gz
  md5: 3f45656baef1f1e9ef9aecefb33d898b

requirements:
  build:
    - python
    - botocore >=1.3.0,<1.4.0
    - jmespath >=0.7.1,<1.0.0
    - futures                 [py27]

  run:
    - python
    - botocore >=1.3.0,<1.4.0
    - jmespath >=0.7.1,<1.0.0
    - futures                 [py27]

test:
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3

about:
  home: https://github.com/boto/boto3
  license: Apache Software License
  summary: 'The AWS SDK for Python'
