name: dask-distributed
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - asyncssh
  - bokeh
  - click
  - cloudpickle
  - cython
  - dask
  - flake8
  - h5py
  - ipykernel
  - ipywidgets
  - joblib
  - jupyter_client
  - msgpack-python>=0.6.0
  - netcdf4
  - paramiko
  - prometheus_client
  - psutil
  - pytest>=4
  - pytest-asyncio<0.14.0
  - pytest-faulthandler
  - pytest-repeat
  - pytest-timeout
  - requests
  - scikit-learn
  - scipy
  - sortedcollections
  - tblib>=1.5.0
  - toolz
  - tornado=6
  - zstandard
  - pickle5>=0.0.11
  - numba
  - pip:
      - git+https://github.com/dask/dask@master
      - git+https://github.com/joblib/joblib.git@master
      - git+https://github.com/dask/zict@master
      - git+https://github.com/intake/filesystem_spec.git@master
      - git+https://github.com/dask/s3fs.git@master
      - keras
