version: 1

# logging:
#   distributed: info
#   distributed.client: warning
#   bokeh: critical
#   # http://stackoverflow.com/questions/21234772/python-tornado-disable-logging-to-stderr
#   tornado: critical
#   tornado.application: error


#####################
# Scheduler options #
#####################
#
# bandwidth: 100000000    # 100 MB/s estimated worker-worker bandwidth
# allowed-failures: 3     # number of retries before a task is considered bad
# pdb-on-err: False       # enter debug mode on scheduling error
# transition-log-length: 100000
# work-stealing: True     # workers should steal tasks from each other
# worker-ttl: null        # like '60s'. Time to live for workers.  They must heartbeat faster than this


##################
# Worker options #
##################
#
# multiprocessing-method: forkserver
# use-file-locking: True
# profile-interval: 10ms          # Time between statistical profiling queries
# profile-cycle-interval: 1000ms  # Time between starting new profile

# Fractions of worker memory at which we take action to avoid memory blowup
# Set any of the lower three values to False to turn off the behavior entirely
#
# worker-memory-target: 0.60  # target fraction to stay below
# worker-memory-spill: 0.70  # fraction at which we spill to disk
# worker-memory-pause: 0.80  # fraction at which we pause worker threads
# worker-memory-terminate: 0.95  # fraction at which we terminate the worker


##################
# Client Options #
##################

# client-heartbeat-interval: 5s  # time between client heartbeats


#########################
# Communication options #
#########################
#
# compression: auto
# connect-timeout: 10s    # seconds delay before connecting fails
# tcp-timeout: 30s        # seconds delay before calling an unresponsive connection dead
# default-scheme: tcp
# require-encryption: False   # whether to require encryption on non-local comms
# socket-backlog: 2048
# recent-messages-log-length: 0  # number of messages to keep for debugging

# tls:
#   ca-file: xxx.pem
#   scheduler:
#     key: xxx.pem
#     cert: xxx.pem
#   worker:
#     key: xxx.pem
#     cert: xxx.pem
#   client:
#     key: xxx.pem
#     cert: xxx.pem
#   ciphers:
#     ECDHE-ECDSA-AES128-GCM-SHA256


###################
# Bokeh dashboard #
###################
#
# bokeh-export-tool: False
# diagnostics-link: "http://{host}:{port}/status"

##################
# Administrative #
##################
#
# tick-time: 20ms         # time between event loop health checks
# tick-maximum-delay: 3s  # time allowed before triggering a warning

# log-length: 10000  # default length of logs to keep in memory
# log-format: '%(name)s - %(levelname)s - %(message)s'
