logging: 
  distributed: info
  distributed.client: warning
  bokeh: critical
  # http://stackoverflow.com/questions/21234772/python-tornado-disable-logging-to-stderr
  tornado: critical
  tornado.application: error

compression: auto

# Scheduler options
bandwidth: 100000000    # 100 MB/s estimated worker-worker bandwidth
allowed-failures: 3     # number of retries before a task is considered bad
pdb-on-err: False       # enter debug mode on scheduling error
transition-log-length: 100000 

# Worker options
multiprocessing-method: forkserver

# Communication options
tcp-timeout: 30         # seconds delay before calling an unresponsive connection dead
default-scheme: tcp
require-encryption: False   # whether to require encryption on non-local comms
#tls:
    #ca-file: xxx.pem
    #scheduler:
        #key: xxx.pem
        #cert: xxx.pem
    #worker:
        #key: xxx.pem
        #cert: xxx.pem
    #client:
        #key: xxx.pem
        #cert: xxx.pem
    #ciphers:
        #ECDHE-ECDSA-AES128-GCM-SHA256

# Bokeh web dashboard
bokeh-export-tool: False
