package:
  name: distributed
  version: "1.9.5"

source:
  path: ../

requirements:
  build:
    - python
    - tornado
    - toolz
    - cloudpickle
    - dask
    - click
    - boto3
    - locket
    - six
    - tblib
    - joblib
    - lz4
    - psutil

  run:
    - python
    - tornado
    - toolz
    - cloudpickle
    - dask
    - click
    - boto3
    - locket
    - six
    - tblib
    - joblib
    - lz4
    - psutil

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.diagnostics
    - distributed.http

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD
  summary: 'Distributed computing'
