name: Linting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  checks:
    name: prek hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: j178/prek-action@v1.1.1
