name: Windows CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7"]

    env:
      # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
      # /E:ON and /V:ON options are not enabled in the batch script intepreter
      # See: http://stackoverflow.com/a/13751649/163740
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous_integration\\run_with_env.cmd"
      JUNIT_OUT: junit-results.xml

    steps:
      - uses: actions/checkout@v1
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: testenv
      - shell: cmd /C CALL {0}
        run: continuous_integration\\setup_conda_environment.cmd
      - shell: cmd /C CALL {0}
        run: continuous_integration\\build.cmd
      - shell: cmd /C CALL {0}
        run: "%CMD_IN_ENV% continuous_integration\\run_tests.cmd"
