name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: continuous_integration/environment-${{ matrix.python-version }}.yaml
          activate-environment: dask-distributed
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        run: |
          source continuous_integration/scripts/install.sh
          source continuous_integration/scripts/setup-ssh.sh

      - name: Test
        shell: bash -l {0}
        run: source continuous_integration/scripts/run_tests.sh

      - name: Coverage
        shell: bash -l {0}
        if: ${{ matrix.os == 'ubuntu-latest' &&  matrix.python-version == '3.8' }}
        run: coverage report; python -m pip install -q coveralls ; coveralls
