name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-issue-stale: -1
          days-before-stale: 180
          stale-pr-message: 'This PR has been closed because it has been inactive for over 180 days.'
